= Bundling real-world JavaFX applications
Dr.-Ing. Michael Paus, mpMediaSoft GmbH
Version 1.0.0, 2020-02-16
:doctype: article
:encoding: utf-8
:lang: en
:toc: left
:numbered:

[.lead]
A summary of my lessons learned bundling real-world JavaFX application with
various different techniques.

== Bundle sizes

The following table shows the resulting executable bundle sizes (not installer bundles)
resulting from the various bundling techniques.

.Table Bundle sizes
|===
|Technique |Size

|jpackage
|220.7 MB

|jpackage + jlink
|75.9 MB

|native
|100.3 MB
|===

In this table the following techniques are compared:

* jpackage
  ** Pure jpackage bundling its own JRE (14 EA)
* jpackage + jlink
  ** Jpackage bundling a custom JRE (14 EA) created via jlink.
* native
  ** GluonHQ client-maven-plugin + substrate building on GraalVM/native-image (19.3.1)
  
The jpackage + jlink variant could be further improved because the library folder allone,
which contains all the external jars which are linked, has a size of almost 35 MB and from
many jars I only use a tiny fraction of their whole content.

I will try to further shrink that via ProGuard. If that could also be applied to the JRE
itself, then I am pretty sure that the total size could be brought down to less than 40 MB.

The native variant is in this respect disappointing though. All the potential optimizations
that a tool like ProGuard could still apply to the other variants are, according to the
documentation, already done by the native variant, which leaves no more opportinity for
furhter optimizations.
In addition to that the native variant is not even feature complete. E.g., it only supports
a single locale which of course reduces the size of the resulting bundle in a non-acceptable way. Some normally used
code is also not included because it is currently not supported.